# -*- coding: utf-8 -*-
"""AI_REAL_SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8e1qoj1jCjxq2xOuiePCx-jIt0nMNiW

# **SVM MODEL**
"""

import os
import argparse
import pickle
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from pathlib import Path
from PIL import Image
from tqdm import tqdm

# Feature extraction
from skimage.feature import graycomatrix, graycoprops, local_binary_pattern
from skimage.color import rgb2gray
from scipy.fft import fft2, fftshift
from scipy.stats import kurtosis, skew

# ML
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score, roc_curve
)

IMG_SIZE       = (224, 224)   # resize all images to this
LBP_RADIUS     = 3
LBP_N_POINTS   = 8 * LBP_RADIUS
LBP_METHOD     = "uniform"
GLCM_DISTANCES = [1, 3]
GLCM_ANGLES    = [0, np.pi/4, np.pi/2, 3*np.pi/4]
RANDOM_STATE   = 42

def load_image(path: str) -> np.ndarray:
    """Load and resize image to RGB numpy array."""
    img = Image.open(path).convert("RGB").resize(IMG_SIZE)
    return np.array(img)

def extract_color_histogram(img: np.ndarray, bins: int = 32) -> np.ndarray:
    """Per-channel color histograms (R, G, B) — normalized."""
    feats = []
    for ch in range(3):
        hist, _ = np.histogram(img[:, :, ch], bins=bins, range=(0, 256))
        hist = hist.astype(float) / hist.sum()
        feats.append(hist)
    return np.concatenate(feats)

def extract_color_stats(img: np.ndarray) -> np.ndarray:
    """Mean, std, skewness, kurtosis per channel."""
    feats = []
    for ch in range(3):
        ch_data = img[:, :, ch].astype(float).ravel()
        feats.extend([
            ch_data.mean(),
            ch_data.std(),
            skew(ch_data),
            kurtosis(ch_data),
        ])
    return np.array(feats)

def extract_lbp(img: np.ndarray) -> np.ndarray:
    """Local Binary Pattern texture histogram."""
    gray = rgb2gray(img)
    gray_uint8 = (gray * 255).astype(np.uint8)
    lbp = local_binary_pattern(gray_uint8, LBP_N_POINTS, LBP_RADIUS, LBP_METHOD)
    n_bins = LBP_N_POINTS + 2
    hist, _ = np.histogram(lbp.ravel(), bins=n_bins, range=(0, n_bins))
    hist = hist.astype(float) / hist.sum()
    return hist

def extract_glcm(img: np.ndarray) -> np.ndarray:
    """Gray-Level Co-occurrence Matrix — contrast, dissimilarity, homogeneity, energy, correlation."""
    gray = rgb2gray(img)
    gray_uint8 = (gray * 255).astype(np.uint8)
    glcm = graycomatrix(
        gray_uint8,
        distances=GLCM_DISTANCES,
        angles=GLCM_ANGLES,
        levels=256,
        symmetric=True,
        normed=True,
    )
    props = ["contrast", "dissimilarity", "homogeneity", "energy", "correlation"]
    feats = []
    for prop in props:
        val = graycoprops(glcm, prop)   # shape: (len(distances), len(angles))
        feats.extend(val.ravel())
    return np.array(feats)

def extract_frequency_features(img: np.ndarray) -> np.ndarray:
    """
    FFT-based frequency spectrum features.
    AI-generated images often show artifacts in the frequency domain
    (e.g., grid patterns from upsampling, diffusion noise structure).
    """
    gray = rgb2gray(img)
    f = fftshift(fft2(gray))
    magnitude = np.log1p(np.abs(f))

    h, w = magnitude.shape
    cy, cx = h // 2, w // 2

    # Radial energy in 4 frequency bands
    Y, X = np.ogrid[:h, :w]
    R = np.sqrt((X - cx)**2 + (Y - cy)**2)
    max_r = min(cx, cy)
    band_edges = np.linspace(0, max_r, 5)

    feats = []
    for i in range(4):
        mask = (R >= band_edges[i]) & (R < band_edges[i + 1])
        feats.append(magnitude[mask].mean())
        feats.append(magnitude[mask].std())

    # Horizontal / Vertical energy asymmetry (GAN checkerboard artifacts)
    h_energy = magnitude[cy - 2:cy + 2, :].mean()
    v_energy = magnitude[:, cx - 2:cx + 2].mean()
    feats.append(h_energy)
    feats.append(v_energy)
    feats.append(h_energy / (v_energy + 1e-8))

    return np.array(feats)

def extract_noise_features(img: np.ndarray) -> np.ndarray:
    """
    High-frequency noise residual statistics.
    Computed by subtracting a smoothed version and analysing the residual.
    AI images often have very uniform, structured noise.
    """
    from PIL import ImageFilter
    pil = Image.fromarray(img)
    blurred = np.array(pil.filter(ImageFilter.GaussianBlur(radius=2)))
    residual = img.astype(float) - blurred.astype(float)

    feats = []
    for ch in range(3):
        r = residual[:, :, ch].ravel()
        feats.extend([r.mean(), r.std(), kurtosis(r), skew(r)])
    return np.array(feats)

def extract_features(img: np.ndarray) -> np.ndarray:
    """Concatenate all feature groups into one feature vector."""
    return np.concatenate([
        extract_color_histogram(img),   #  96
        extract_color_stats(img),        #  12
        extract_lbp(img),                #  26
        extract_glcm(img),               #  40
        extract_frequency_features(img), #  11
        extract_noise_features(img),     #  12
    ])

SUPPORTED_EXT = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tiff"}

def load_dataset(dataset_dir: str):
    """
    Loads images from dataset/real and dataset/ai folders.
    Returns X (features), y (labels: 0=real, 1=ai), paths.
    """
    dataset_dir = Path(dataset_dir)
    real_dir = dataset_dir / "real"
    ai_dir   = dataset_dir / "ai"

    assert real_dir.exists(), f"Missing folder: {real_dir}"
    assert ai_dir.exists(),   f"Missing folder: {ai_dir}"

def load_dataset(dataset_dir: str):
    """
    Loads images from dataset/real and dataset/ai folders.
    Returns X (features), y (labels: 0=real, 1=ai), paths.
    """
    dataset_dir = Path(dataset_dir)
    # Changed 'real' to 'Real' and 'ai' to 'AI' to match actual folder names
    real_dir = dataset_dir / "Real"
    ai_dir   = dataset_dir / "AI"

    assert real_dir.exists(), f"Missing folder: {real_dir}"
    assert ai_dir.exists(),   f"Missing folder: {ai_dir}"

    def gather(folder, label):
        paths = [p for p in folder.iterdir() if p.suffix.lower() in SUPPORTED_EXT]
        return paths, [label] * len(paths)

    real_paths, real_labels = gather(real_dir, 0)
    ai_paths,   ai_labels   = gather(ai_dir,   1)

    all_paths  = real_paths + ai_paths
    all_labels = real_labels + ai_labels

    print(f"\nDataset: {len(real_paths)} real | {len(ai_paths)} AI")
    print(f"Extracting features from {len(all_paths)} images …")

    X, y, valid_paths = [], [], []
    for path, label in tqdm(zip(all_paths, all_labels), total=len(all_paths)):
        try:
            img  = load_image(str(path))
            feat = extract_features(img)
            X.append(feat)
            y.append(label)
            valid_paths.append(path)
        except Exception as e:
            print(f"Skipping {path.name}: {e}")

    return np.array(X), np.array(y), valid_paths

def build_pipeline() -> Pipeline:
    """StandardScaler + RBF-kernel SVM."""
    return Pipeline([
        ("scaler", StandardScaler()),
        ("svm",    SVC(
            kernel="rbf",
            C=10,
            gamma="scale",
            probability=True,       # needed for AUC / predict_proba
            class_weight="balanced",
            random_state=RANDOM_STATE,
        )),
    ])

def train(dataset_dir: str, model_path: str):
    X, y, _ = load_dataset(dataset_dir)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
    )

    print("\nTraining SVM …")
    clf = build_pipeline()
    clf.fit(X_train, y_train)

    # ── Evaluation on hold-out set ────────────────────────────────────────
    y_pred  = clf.predict(X_test)
    y_proba = clf.predict_proba(X_test)[:, 1]

    print("\n── Test-set Results ─────────────────────────────────────────────")
    print(classification_report(y_test, y_pred, target_names=["real", "ai"]))

    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix (rows=actual, cols=predicted):")
    print(f"             Pred:Real  Pred:AI")
    print(f"Actual:Real  {cm[0,0]:>9}  {cm[0,1]:>7}")
    print(f"Actual:AI    {cm[1,0]:>9}  {cm[1,1]:>7}")

    auc = roc_auc_score(y_test, y_proba)
    print(f"\nROC-AUC: {auc:.4f}")

    # ── 5-fold cross-validation on full dataset ───────────────────────────
    print("\nRunning 5-fold cross-validation on full dataset …")
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    cv_scores = cross_val_score(build_pipeline(), X, y, cv=cv, scoring="roc_auc", n_jobs=-1)
    print(f"CV ROC-AUC: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

    # ── Save model ────────────────────────────────────────────────────────
    with open(model_path, "wb") as f:
        pickle.dump(clf, f)
    print(f"\n Model saved to: {model_path}")

def evaluate(dataset_dir: str, model_path: str):
    with open(model_path, "rb") as f:
        clf = pickle.load(f)

    X, y, paths = load_dataset(dataset_dir)
    y_pred  = clf.predict(X)
    y_proba = clf.predict_proba(X)[:, 1]

    print("\n── Full Dataset Evaluation ─────────────────────────────────────────")
    print(classification_report(y, y_pred, target_names=["real", "ai"]))
    print(f"ROC-AUC: {roc_auc_score(y, y_proba):.4f}")

def predict_image(image_path: str, model_path: str):
    with open(model_path, "rb") as f:
        clf = pickle.load(f)

    img   = load_image(image_path)
    feat  = extract_features(img).reshape(1, -1)
    label = clf.predict(feat)[0]
    proba = clf.predict_proba(feat)[0]

    label_str = "AI-Generated" if label == 1 else "Real"
    confidence = proba[label] * 100

    print(f"\nImage  : {image_path}")
    print(f"Result : {label_str}  (confidence: {confidence:.1f}%)")
    print(f"  P(real) = {proba[0]*100:.1f}%")
    print(f"  P(ai)   = {proba[1]*100:.1f}%")
    return label_str, proba

import sys
import argparse
import os

def parse_args():
    p = argparse.ArgumentParser(description="AI vs Real Image Detector (SVM)")
    p.add_argument("--mode",      required=True, choices=["train", "eval", "predict"])
    p.add_argument("--dataset",   default="/content/dataset/data_set_svm",
                  help="Path to dataset folder")
    p.add_argument("--model_out", default="model_svm.pkl",  help="Model save/load path")
    p.add_argument("--image",     default=None,             help="Image path (predict mode)")
    return p.parse_args()

if __name__ == "__main__":
    original_argv = sys.argv[:]

    # --- Dataset setup start ---
    print("Setting up dataset...")
    real_dir = '/content/dataset/data_set_svm/Real'
    ai_dir = '/content/dataset/data_set_svm/AI'

    # Check if the directories already exist and are populated to avoid re-extraction
    if not (os.path.exists(real_dir) and len(os.listdir(real_dir)) > 0 and \
            os.path.exists(ai_dir) and len(os.listdir(ai_dir)) > 0):
        print("Dataset not found or incomplete. Extracting...")
        !sudo apt-get install p7zip-full -y > /dev/null
        !mkdir -p /content/dataset/data_set_svm/Real
        !mkdir -p /content/dataset/data_set_svm/AI

        # Use 7z to extract, which is very robust against zip corruption
        !7z x /content/data_set_svm.zip -o/content/temp_7z -y > /dev/null

        # Recursive move for any found image folders
        !find /content/temp_7z -type d -iname "real" -exec sh -c 'mv "$1"/* /content/dataset/data_set_svm/Real/' _ {} \;
        !find /content/temp_7z -type d \( -iname "fake" -o -iname "ai" \) -exec sh -c 'mv "$1"/* /content/dataset/data_set_svm/AI/' _ {} \;

        print(f"Extraction complete.")
        print(f"Real images: {len(os.listdir('/content/dataset/data_set_svm/Real')) if os.path.exists('/content/dataset/data_set_svm/Real') else 0}")
        print(f"AI images:   {len(os.listdir('/content/dataset/data_set_svm/AI')) if os.path.exists('/content/dataset/data_set_svm/AI') else 0}")
    else:
        print("Dataset directories already exist and are populated. Skipping extraction.")
    # --- Dataset setup end ---

    # Pointing specifically to the recovered dataset path
    sys.argv = [
        'colab_script.py',
        '--mode', 'train',
        '--dataset', '/content/dataset/data_set_svm',
        '--model_out', 'model_svm.pkl'
    ]

    try:
        args = parse_args()

        if args.mode == "train":
            train(args.dataset, args.model_out)

        elif args.mode == "eval":
            evaluate(args.dataset, args.model_out)

        elif args.mode == "predict":
            assert args.image, "--image is required in predict mode"
            predict_image(args.image, args.model_out)
    finally:
        sys.argv = original_argv

!ls -R /content/dataset/data_set_svm/

import os
def list_files(startpath):
    for root, dirs, files in os.walk(startpath):
        level = root.replace(startpath, '').count(os.sep)
        indent = ' ' * 4 * (level)
        print(f'{indent}{os.path.basename(root)}/')
        subindent = ' ' * 4 * (level + 1)
        for f in files[:5]: # limit to 5 files per dir for brevity
            print(f'{subindent}{f}')

if os.path.exists('./dataset'):
    list_files('./dataset')
else:
    print('Directory "./dataset" does not exist.')

!sudo apt-get install p7zip-full -y > /dev/null
!mkdir -p /content/dataset/data_set_svm/Real
!mkdir -p /content/dataset/data_set_svm/AI

# Use 7z to extract, which is very robust against zip corruption
!7z x /content/data_set_svm.zip -o/content/temp_7z -y > /dev/null

# Recursive move for any found image folders
!find /content/temp_7z -type d -iname "real" -exec sh -c 'mv "$1"/* /content/dataset/data_set_svm/Real/' _ {} \;
!find /content/temp_7z -type d \( -iname "fake" -o -iname "ai" \) -exec sh -c 'mv "$1"/* /content/dataset/data_set_svm/AI/' _ {} \;

import os
print(f"Extraction complete.")
print(f"Real images: {len(os.listdir('/content/dataset/data_set_svm/Real')) if os.path.exists('/content/dataset/data_set_svm/Real') else 0}")
print(f"AI images:   {len(os.listdir('/content/dataset/data_set_svm/AI')) if os.path.exists('/content/dataset/data_set_svm/AI') else 0}")

"""To verify the dataset folder structure, you can use the `ls -R` command to list all files and directories recursively within the `./dataset` directory."""

!ls -R ./dataset