# -*- coding: utf-8 -*-
"""AI_vs_REAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lOkMV_WVmp5DNBPC5cTzf0DuGUYOa3I

# **AI vs Real Image Detection using Deep Learning**
"""

from google.colab import files
uploaded = files.upload()

import zipfile

zip_ref = zipfile.ZipFile('archive (2).zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

import os
import random
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns

from PIL import Image
from pathlib import Path
from collections import Counter

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)

print("TensorFlow version:", tf.__version__)
print("Keras version:", keras.__version__)
print("All libraries imported successfully!")

from google.colab import drive
drive.mount('/content/drive')

DATASET_PATH = "/content"

TRAIN_DIR = os.path.join(DATASET_PATH, "train")
TEST_DIR  = os.path.join(DATASET_PATH, "test")

print("Train directory:", TRAIN_DIR)
print("Test directory :", TEST_DIR)

for split, path in [("Train/Real", os.path.join(TRAIN_DIR, "Real")),
                    ("Train/Fake", os.path.join(TRAIN_DIR, "Fake")),
                    ("Test/Real",  os.path.join(TEST_DIR,  "Real")),
                    ("Test/Fake",  os.path.join(TEST_DIR,  "Fake"))]:
    count = len(os.listdir(path)) if os.path.exists(path) else "PATH NOT FOUND"
    print(f"  {split}: {count} images")

"""**Configuration**"""

IMG_HEIGHT   = 128
IMG_WIDTH    = 128
BATCH_SIZE   = 32
EPOCHS       = 30
LEARNING_RATE = 0.001
SEED         = 42

CLASS_NAMES  = ["Fake", "Real"]
tf.random.set_seed(SEED)
np.random.seed(SEED)

"""**Data Cleaning**"""

def remove_corrupt_images(directory):
    removed = 0
    for root, _, files in os.walk(directory):
        for fname in files:
            fpath = os.path.join(root, fname)
            try:
                with Image.open(fpath) as img:
                    img.verify()
            except Exception:
                print(f"  Removing corrupt file: {fpath}")
                os.remove(fpath)
                removed += 1
    return removed
removed_train = remove_corrupt_images(TRAIN_DIR)
removed_test  = remove_corrupt_images(TEST_DIR)
print(f"Found and removed {removed_train} corrupt training images.")
print(f"Found and removed {removed_test}  corrupt test images.")

"""**Exploratory Data Analysis (EDA)**"""

import os

train_real_count = len(os.listdir(os.path.join(TRAIN_DIR, "Real"))) if os.path.exists(os.path.join(TRAIN_DIR, "Real")) else 0
train_fake_count = len(os.listdir(os.path.join(TRAIN_DIR, "Fake"))) if os.path.exists(os.path.join(TRAIN_DIR, "Fake")) else 0
test_real_count  = len(os.listdir(os.path.join(TEST_DIR,  "Real")))  if os.path.exists(os.path.join(TEST_DIR,  "Real")) else 0
test_fake_count  = len(os.listdir(os.path.join(TEST_DIR,  "Fake")))  if os.path.exists(os.path.join(TEST_DIR,  "Fake")) else 0

print("\n--Dataset Summary--")
print(f"-Training ->\nReal:{train_real_count}\nFake: {train_fake_count}\nTotal: {train_real_count + train_fake_count}")
print(f"-Test ->\nReal:{test_real_count}\nFake:{test_fake_count}\nTotal:{test_real_count  + test_fake_count}")

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
for ax, (title, real, fake) in zip(axes, [
        ("Training Set Distribution",  train_real_count, train_fake_count),
        ("Test Set Distribution",       test_real_count,  test_fake_count)]):
    ax.bar(["Real", "Fake"], [real, fake], color=["steelblue", "tomato"], edgecolor="black")
    ax.set_title(title, fontsize=13)
    ax.set_ylabel("Number of Images")
    for i, v in enumerate([real, fake]):
        ax.text(i, v + 5, str(v), ha="center", fontweight="bold")
plt.tight_layout()
plt.savefig("/content/class_distribution.png", dpi=150)
plt.show()
print("Class distribution chart saved.")

def show_sample_images(directory, class_name, n=6, title_prefix=""):
    folder = os.path.join(directory, class_name)
    # Check if the folder exists before proceeding
    if not os.path.exists(folder):
        print(f"Error: Directory not found: {folder}")
        return

    files  = random.sample(os.listdir(folder), min(n, len(os.listdir(folder))))
    if not files:
        print(f"Error: No images found in {folder}")
        return

    fig, axes = plt.subplots(1, n, figsize=(15, 3))
    fig.suptitle(f"{title_prefix} — {class_name} samples", fontsize=13)
    for ax, fname in zip(axes, files):
        img = mpimg.imread(os.path.join(folder, fname))
        ax.imshow(img)
        ax.axis("off")
    plt.tight_layout()
    plt.show()

show_sample_images(TRAIN_DIR, "Real", title_prefix="Training")
show_sample_images(TRAIN_DIR, "Fake", title_prefix="Training")

def collect_sizes(directory):
    sizes = []
    for root, _, files in os.walk(directory):
        for fname in files:
            try:
                with Image.open(os.path.join(root, fname)) as img:
                    sizes.append(img.size)
            except Exception:
                pass
    return sizes

print("Collecting image sizes from training set (may take a moment) …")
sizes = collect_sizes(TRAIN_DIR)
widths, heights = zip(*sizes)

!ls -R /content

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].hist(widths,  bins=30, color="steelblue", edgecolor="black")
axes[0].set_title("Width Distribution");  axes[0].set_xlabel("Width (px)")
axes[1].hist(heights, bins=30, color="coral",     edgecolor="black")
axes[1].set_title("Height Distribution"); axes[1].set_xlabel("Height (px)")
plt.tight_layout()
plt.savefig("/content/size_distribution.png", dpi=150)
plt.show()

"""**Image Preprocessing & Data Augmentation**"""

train_datagen = ImageDataGenerator(
    rescale=1.0 / 255,
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode="nearest",
    validation_split=0.15,
)

test_datagen = ImageDataGenerator(rescale=1.0 / 255)

train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    subset="training",
    seed=SEED,
)

val_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    subset="validation",
    seed=SEED,
)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False,
)

print("Class indices:", train_generator.class_indices)
print(f"Training samples: {train_generator.samples}")
print(f"Validation samples: {val_generator.samples}")
print(f"Test samples: {test_generator.samples}")

sample_batch, sample_labels = next(train_generator)
fig, axes = plt.subplots(2, 6, figsize=(16, 6))
fig.suptitle("Sample Preprocessed & Augmented Training Images", fontsize=13)
for i, ax in enumerate(axes.flat):
    ax.imshow(sample_batch[i])
    ax.set_title("Real" if sample_labels[i] == 1 else "Fake", fontsize=9)
    ax.axis("off")
plt.tight_layout()
plt.savefig("/content/augmented_samples.png", dpi=150)
plt.show()

"""# **Build the CNN Model**"""

def build_cnn_model(input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)):
    model = models.Sequential([

        layers.Conv2D(32, (3, 3), activation="relu", padding="same",
                      input_shape=input_shape),
        layers.BatchNormalization(),
        layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        layers.Conv2D(64, (3, 3), activation="relu", padding="same"),
        layers.BatchNormalization(),
        layers.Conv2D(64, (3, 3), activation="relu", padding="same"),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        layers.Conv2D(128, (3, 3), activation="relu", padding="same"),
        layers.BatchNormalization(),
        layers.Conv2D(128, (3, 3), activation="relu", padding="same"),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.4),

        # Classifier head
        layers.Flatten(),
        layers.Dense(256, activation="relu"),
        layers.BatchNormalization(),
        layers.Dropout(0.5),
        layers.Dense(128, activation="relu"),
        layers.Dropout(0.3),
        layers.Dense(1, activation="sigmoid"),
    ], name="AI_vs_Real_CNN")
    return model

model = build_cnn_model()
model.summary()

# Compile
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=LEARNING_RATE),
    loss="binary_crossentropy",
    metrics=["accuracy"],
)

"""**Callbacks**"""

callbacks = [
    EarlyStopping(
        monitor="val_loss",
        patience=6,
        restore_best_weights=True,
        verbose=1,
    ),
    ModelCheckpoint(
        filepath="/content/best_model.keras",
        monitor="val_accuracy",
        save_best_only=True,
        verbose=1,
    ),
    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        min_lr=1e-6,
        verbose=1,
    ),
]

"""**Train the Model**"""

print("\nStarting model training …\n")
history = model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=val_generator,
    callbacks=callbacks,
    verbose=1,
)
print("\nTraining complete!")

"""**Training Curves**"""

def plot_training_history(history):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Accuracy
    axes[0].plot(history.history["accuracy"],     label="Train Accuracy",      color="steelblue")
    axes[0].plot(history.history["val_accuracy"], label="Validation Accuracy", color="orange")
    axes[0].set_title("Model Accuracy", fontsize=13)
    axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Accuracy")
    axes[0].legend(); axes[0].grid(True, alpha=0.3)

    # Loss
    axes[1].plot(history.history["loss"],     label="Train Loss",      color="steelblue")
    axes[1].plot(history.history["val_loss"], label="Validation Loss", color="orange")
    axes[1].set_title("Model Loss", fontsize=13)
    axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Loss")
    axes[1].legend(); axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("/content/training_curves.png", dpi=150)
    plt.show()

plot_training_history(history)

"""**Model Evaluation on Test Set**"""

print("\nEvaluating on test set …")
test_loss, test_accuracy = model.evaluate(test_generator, verbose=1)
print(f"\nTest Loss    : {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")

test_generator.reset()
y_pred_probs = model.predict(test_generator, verbose=1)
y_pred  = (y_pred_probs > 0.5).astype(int).flatten()
y_true  = test_generator.classes

accuracy  = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall    = recall_score(y_true, y_pred)
f1        = f1_score(y_true, y_pred)

print("\n=Evaluation Metrics =")
print(f"Accuracy : {accuracy  * 100:.2f}%")
print(f"Precision: {precision * 100:.2f}%")
print(f"Recall   : {recall    * 100:.2f}%")
print(f"F1 Score : {f1        * 100:.2f}%")
print("=========================================\n")
print("Classification Report:")
print(classification_report(y_true, y_pred, target_names=CLASS_NAMES))

#Confusion Matrix
def plot_confusion_matrix(y_true, y_pred, class_names):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(7, 5))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=class_names,
        yticklabels=class_names,
        linewidths=0.5,
    )
    plt.title("Confusion Matrix", fontsize=14)
    plt.ylabel("Actual Label")
    plt.xlabel("Predicted Label")
    plt.tight_layout()
    plt.savefig("/content/confusion_matrix.png", dpi=150)
    plt.show()

plot_confusion_matrix(y_true, y_pred, CLASS_NAMES)

#Visualise Predictions on Test Images
def visualise_predictions(generator, model, class_names, n=12):
    generator.reset()
    images, labels = next(generator)
    preds = model.predict(images[:n], verbose=0)

    fig, axes = plt.subplots(2, 6, figsize=(18, 7))
    fig.suptitle("Test Image Predictions  (green = correct, red = wrong)", fontsize=13)
    for i, ax in enumerate(axes.flat):
        ax.imshow(images[i])
        pred_label  = class_names[int(preds[i] > 0.5)]
        true_label  = class_names[int(labels[i])]
        confidence  = preds[i][0] if preds[i] > 0.5 else 1 - preds[i][0]
        color = "green" if pred_label == true_label else "red"
        ax.set_title(f"True: {true_label}\nPred: {pred_label} ({confidence:.0%})",
                     color=color, fontsize=8)
        ax.axis("off")
    plt.tight_layout()
    plt.savefig("/content/prediction_samples.png", dpi=150)
    plt.show()

visualise_predictions(test_generator, model, CLASS_NAMES)

#Saving the Final Model
MODEL_SAVE_PATH = "/content/drive/MyDrive/ai_vs_real_model.keras"
model.save(MODEL_SAVE_PATH)
print(f"Model saved to: {MODEL_SAVE_PATH}")

# Also save in legacy .h5 format if needed
MODEL_H5_PATH = "/content/drive/MyDrive/ai_vs_real_model.h5"
model.save(MODEL_H5_PATH)
print(f"Model also saved as .h5: {MODEL_H5_PATH}")

from google.colab import files
files.download("/content/best_model.keras")

